# Generated by Django 3.2.5 on 2021-12-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Image')),
            ],
            options={
                'ordering': ['title', 'created', 'description', 'image', 'video'],
            },
        ),
    ]
